document.writeln("<li style=\"--i: 0\"><a href=\'/\'><span class=\'i_small ri:home-3-fill\'></span> HOME</a></li>");
document.writeln("<li style=\"--i: 1\"><a href=\'/works/\'><span class=\'i_small ri:dashboard-fill\'></span> WORKS</a></li>");
document.writeln("<li style=\"--i: 2\"><a href=\'/articles\'><span class=\'i_small ri:article-fill\'></span> ARTICLES</a></li>");
document.writeln("<li style=\"--i: 3\"><a href=\'/tag/\'><span class=\'i_small ri:price-tag-3-fill\'></span> TAG</a></li>");
document.writeln("<li style=\"--i: 4\"><a href=\'/classification/\'><span class=\'i_small ri:archive-fill\'></span> CLASSIFICATION</a>");
document.writeln("<li style=\"--i: 5\"><a href=\'/friends/\'><span class=\'i_small ri:team-fill\'></span> FRIENDS</a></li>");
document.writeln("<li style=\"--i: 6\"><a href=\'/about/\'><span class=\'i_small ri:information-fill\'></span> ABOUT</a></li><br>");
document.writeln("<li style=\"--i: 7\"><a href=\'//ravelloh.gitee.io/cname"+window.location.pathname+"\'><span class=\'i_small ri:swap-box-fill\'></span> SWAP SERVER</a></li>");
document.writeln("<li style=\"--i: 8\"><a href=\'/admin/\'><span class=\'i_small ri:login-box-fill\'></span> LOG IN</a></li>");
document.writeln("<li style=\"--i: 9\"><a href=\'/analysis/\'><span class=\'i_small ri:bar-chart-box-fill\'></span> ANALYSIS</a></li>");
document.writeln("<b><br><br>Copyright © 2019 - <b id=\'year\'></b> RavelloH.<br> All rights reserved.</b>");
//document.writeln("<br><br><a class=\'info\' style=\'width:88%;margin:0\' href=\'//ravelloh.gitee.io/cname"+window.location.pathname+"\'>数据源:<wbr><strong>"+window.location.hostname+"</strong><br>单击重分配</a>");