name: deploy
on: [push]
  workflow_dispatch:
jobs:
  sync:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:RavelloH/ravelloh.github.io.git"
          destination-repo: "git@gitee.com:ravelloh/ravelloh.git"
  reload-pages:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: reload
        uses: mizuka-wu/gitee-pages-action@v1.0.0
        with:
          repository: RavelloH/ravelloh
          cookie: ${{ secrets.GITEE_COOKIE }}
          branch: main
          https: true
